/* Generated By:JJTree&JavaCC: Do not edit this line. BitLanguageTreeConstants.java */
package tree;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BitLanguageTreeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letter = 5;
  /** RegularExpression Id. */
  int digit = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<letter>",
    "<digit>",
    "\";\"",
    "\"boolean\"",
    "\"int\"",
    "\"{\"",
    "\"}\"",
    "\"if\"",
    "\"(\"",
    "\")\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "\"=\"",
    "\"CUR\"",
    "\"RANDOM\"",
    "\"ENEMY\"",
    "\"[\"",
    "\"]\"",
    "\"||\"",
    "\"&&\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"+\"",
    "\"-\"",
  };

}
