/* Generated By:JavaCC: Do not edit this line. BitLanguageTreeTreeConstants.java Version 5.0 */
package tree;

public interface BitLanguageTreeTreeConstants
{
  public int JJTANALYSE = 0;
  public int JJTSTATEMENT = 1;
  public int JJTDECLARATION = 2;
  public int JJTTYPEID = 3;
  public int JJTID = 4;
  public int JJTBLOCK = 5;
  public int JJTSTATEMENTLIST = 6;
  public int JJTIFSTATEMENT = 7;
  public int JJTWHILESTATEMENT = 8;
  public int JJTRETURNSTATEMENT = 9;
  public int JJTASSIGNMENT = 10;
  public int JJTEXPRESSION = 11;
  public int JJTPRIMARYEXPRESSION = 12;
  public int JJTGLOBALRANDOM = 13;
  public int JJTGLOBALENEMY = 14;
  public int JJTCONDITIONALOREXPRESSION = 15;
  public int JJTCONDITIONALANDEXPRESSION = 16;
  public int JJTEQUALITYEXPRESSION = 17;
  public int JJTRELATIONALEXPRESSION = 18;
  public int JJTADDITIVEEXPRESSION = 19;
  public int JJTUNARYEXPRESSION = 20;
  public int JJTNUM = 21;


  public String[] jjtNodeName = {
    "analyse",
    "statement",
    "declaration",
    "typeID",
    "ID",
    "block",
    "statementList",
    "ifStatement",
    "whileStatement",
    "returnStatement",
    "assignment",
    "expression",
    "primaryExpression",
    "globalRandom",
    "globalEnemy",
    "conditionalOrExpression",
    "conditionalandExpression",
    "equalityExpression",
    "relationalExpression",
    "additiveExpression",
    "unaryExpression",
    "NUM",
  };
}
/* JavaCC - OriginalChecksum=e08069fc60b4df21557cb924298f48ff (do not edit this line) */
